# Generated by Django 4.0 on 2021-02-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compositionDuMahal', '0002_auto_20210210_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(default='', max_length=100)),
                ('fonction', models.CharField(max_length=100)),
                ('image', models.FileField(default=None, upload_to='photos/')),
            ],
            options={
                'verbose_name': 'contact',
            },
        ),
    ]
