# Generated by Django 4.0 on 2021-02-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compositionDuMahal', '0003_presentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='image',
            field=models.FileField(default=None, upload_to='images/'),
        ),
    ]
