# Generated by Django 4.0 on 2021-02-25 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compositionDuMahal', '0004_alter_presentation_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='prenom',
        ),
    ]
