# Generated by Django 4.0 on 2021-02-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compositionDuMahal', '0005_remove_presentation_prenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='metier',
            field=models.CharField(default='', max_length=100),
        ),
    ]
